/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: generated-schema.json
export type Label = {
  text?: string;
  alignment?: "left" | "center" | "right";
  textColor?: "light" | "dark";
  background?: Color;
};

export type TextPost = {
  _id: string;
  _type: "textPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  postDetails?: PostDetails;
  content?: TextBlock;
};

export type TextBlock = {
  _type: "textBlock";
  blockDetails?: BlockDetails;
  customTexts?: Array<
    {
      _key: string;
    } & CustomText
  >;
};

export type CustomPost = {
  _id: string;
  _type: "customPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  postDetails?: PostDetails;
  blocks?: Array<
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & EventsBlock)
    | ({
        _key: string;
      } & MusicBlock)
  >;
};

export type PostDetails = {
  _type: "postDetails";
  category?: string;
  background?: Color;
  label?: Label;
};

export type CustomText = {
  _type: "customText";
  text?: string;
  textSize?: "small" | "medium" | "large";
  textAlignment?: "left" | "center" | "right";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type MusicBlock = {
  _type: "musicBlock";
  blockDetails?: BlockDetails;
  artist?: string;
  name?: string;
  coverArt?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  musicTracks?: Array<
    {
      _key: string;
    } & MusicTrack
  >;
};

export type EventsBlock = {
  _type: "eventsBlock";
  blockDetails?: BlockDetails;
  title?: string;
  events?: Array<
    {
      _key: string;
    } & Event
  >;
};

export type BlockDetails = {
  _type: "blockDetails";
  textColor?: "light" | "dark";
  background?: Color;
};

export type MusicTrack = {
  _type: "musicTrack";
  name?: string;
  artist?: string;
  audioFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type Event = {
  _type: "event";
  name?: string;
  date?: string;
  location?: string;
  startTime?:
    | "12:00 AM"
    | "12:30 AM"
    | "1:00 AM"
    | "1:30 AM"
    | "2:00 AM"
    | "2:30 AM"
    | "3:00 AM"
    | "3:30 AM"
    | "4:00 AM"
    | "4:30 AM"
    | "5:00 AM"
    | "5:30 AM"
    | "6:00 AM"
    | "6:30 AM"
    | "7:00 AM"
    | "7:30 AM"
    | "8:00 AM"
    | "8:30 AM"
    | "9:00 AM"
    | "9:30 AM"
    | "10:00 AM"
    | "10:30 AM"
    | "11:00 AM"
    | "11:30 AM"
    | "12:00 PM"
    | "12:30 PM"
    | "1:00 PM"
    | "1:30 PM"
    | "2:00 PM"
    | "2:30 PM"
    | "3:00 PM"
    | "3:30 PM"
    | "4:00 PM"
    | "4:30 PM"
    | "5:00 PM"
    | "5:30 PM"
    | "6:00 PM"
    | "6:30 PM"
    | "7:00 PM"
    | "7:30 PM"
    | "8:00 PM"
    | "8:30 PM"
    | "9:00 PM"
    | "9:30 PM"
    | "10:00 PM"
    | "10:30 PM"
    | "11:00 PM"
    | "11:30 PM";
  endTime?:
    | "12:00 AM"
    | "12:30 AM"
    | "1:00 AM"
    | "1:30 AM"
    | "2:00 AM"
    | "2:30 AM"
    | "3:00 AM"
    | "3:30 AM"
    | "4:00 AM"
    | "4:30 AM"
    | "5:00 AM"
    | "5:30 AM"
    | "6:00 AM"
    | "6:30 AM"
    | "7:00 AM"
    | "7:30 AM"
    | "8:00 AM"
    | "8:30 AM"
    | "9:00 AM"
    | "9:30 AM"
    | "10:00 AM"
    | "10:30 AM"
    | "11:00 AM"
    | "11:30 AM"
    | "12:00 PM"
    | "12:30 PM"
    | "1:00 PM"
    | "1:30 PM"
    | "2:00 PM"
    | "2:30 PM"
    | "3:00 PM"
    | "3:30 PM"
    | "4:00 PM"
    | "4:30 PM"
    | "5:00 PM"
    | "5:30 PM"
    | "6:00 PM"
    | "6:30 PM"
    | "7:00 PM"
    | "7:30 PM"
    | "8:00 PM"
    | "8:30 PM"
    | "9:00 PM"
    | "9:30 PM"
    | "10:00 PM"
    | "10:30 PM"
    | "11:00 PM"
    | "11:30 PM";
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Label
  | TextPost
  | TextBlock
  | CustomPost
  | PostDetails
  | CustomText
  | SanityFileAssetReference
  | MusicBlock
  | EventsBlock
  | BlockDetails
  | MusicTrack
  | Event
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

export declare const internalGroqTypeReferenceTo: unique symbol;
