/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: generated-schema.json
export type Background = {
  type?: "transparent" | "color" | "image";
  color?: Color;
  image?: BackgroundImage;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category?: string;
  textColor?: "light" | "dark";
  background?: Color;
  labelText?: string;
  labelAlignment?: "left" | "center" | "right";
  labelTextColor?: "light" | "dark";
  labelBackground?: Color;
  blocks?: Array<
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & EventsBlock)
    | ({
        _key: string;
      } & MusicBlock)
    | ({
        _key: string;
      } & PhotoBlock)
    | ({
        _key: string;
      } & ContactFormBlock)
  >;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type ContactFormBlock = {
  _type: "contactFormBlock";
  blockColors?: BlockColors;
  title?: string;
};

export type PhotoBlock = {
  _type: "photoBlock";
  photos?: Array<
    {
      _key: string;
    } & ImageInfo
  >;
};

export type TextBlock = {
  _type: "textBlock";
  blockColors?: BlockColors;
  customTexts?: Array<
    {
      _key: string;
    } & CustomText
  >;
};

export type MusicBlock = {
  _type: "musicBlock";
  blockColors?: BlockColors;
  artist?: string;
  name?: string;
  coverArt?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  musicTracks?: Array<
    {
      _key: string;
    } & MusicTrack
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type EventsBlock = {
  _type: "eventsBlock";
  blockColors?: BlockColors;
  title?: string;
  events?: Array<
    {
      _key: string;
    } & Event
  >;
};

export type BlockColors = {
  _type: "blockColors";
  textColor?: "inherit" | "light" | "dark";
  background?: Background;
};

export type ImageInfo = {
  _type: "imageInfo";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type CustomText = {
  _type: "customText";
  text?: string;
  textSize?: "small" | "medium" | "large";
  textAlignment?: "left" | "center" | "right";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type MusicTrack = {
  _type: "musicTrack";
  name?: string;
  artist?: string;
  audioFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type Event = {
  _type: "event";
  name?: string;
  location?: string;
  date?: string;
  startTime?: string;
  endTime?: string;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Background
  | SanityImageAssetReference
  | BackgroundImage
  | Post
  | Color
  | ContactFormBlock
  | PhotoBlock
  | TextBlock
  | MusicBlock
  | SanityImageCrop
  | SanityImageHotspot
  | EventsBlock
  | BlockColors
  | ImageInfo
  | CustomText
  | SanityFileAssetReference
  | MusicTrack
  | Event
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

export declare const internalGroqTypeReferenceTo: unique symbol;
